layout_spectrum: 0.2275985
color:
  saturation: 0.8046594
  brandStrength: 0.3049741
  lightness: 0.239546
  rhythmicContrast: 0.969424
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.07347666
name: Lola's Photography
